# Generated by Django 3.1.4 on 2021-10-03 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('grup_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('grup_nombre', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': '"academico"."grupo"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('mate_codigomateria', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('mate_nombre', models.CharField(max_length=100)),
                ('mate_capacidad', models.IntegerField(blank=True, null=True)),
                ('mate_horaspracticas', models.IntegerField(blank=True, null=True)),
                ('mate_horasteoricas', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': '"academico"."materia"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PensumMateria',
            fields=[
                ('pens_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('pema_periodo', models.IntegerField()),
                ('pema_estado', models.IntegerField()),
            ],
            options={
                'db_table': '"academico"."pensummateria"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PeriodoUniversidad',
            fields=[
                ('peun_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('peun_ano', models.IntegerField()),
                ('peun_periodo', models.CharField(max_length=15)),
                ('peun_fechainicio', models.DateField()),
                ('peun_fechafin', models.DateField()),
            ],
            options={
                'db_table': '"academico"."periodouniversidad"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Programa',
            fields=[
                ('prog_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('prog_nombre', models.CharField(max_length=150)),
                ('prog_codigoprograma', models.CharField(blank=True, max_length=50, null=True)),
                ('prog_estado', models.IntegerField()),
            ],
            options={
                'db_table': '"academico"."programa"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Unidad',
            fields=[
                ('unid_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('unid_nombre', models.CharField(max_length=100)),
                ('unid_codigo', models.CharField(blank=True, max_length=40, null=True)),
            ],
            options={
                'db_table': '"academico"."unidad"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UnidadPrograma',
            fields=[
                ('unpr_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('unpr_cupominimo', models.IntegerField(blank=True, null=True)),
                ('unpr_cupomaximo', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': '"academico"."unidadprograma"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EstudiantePensum',
            fields=[
                ('estp_id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='MatriculaAcademica',
            fields=[
                ('maac_id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
