# Generated by Django 3.1.4 on 2021-10-03 21:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academicoglobal', '0001_initial'),
        ('general', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConceptosPraticas',
            fields=[
                ('copr_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('copr_nombre', models.CharField(max_length=300)),
                ('tiin_descripcion', models.TextField(blank=True, null=True)),
                ('copr_requierebase', models.IntegerField(default=0)),
                ('copr_valorbase', models.FloatField(blank=True, null=True)),
                ('copr_estado', models.IntegerField(blank=True, default=1, null=True)),
                ('copr_registradorpor', models.CharField(blank=True, max_length=30, null=True)),
                ('copr_fecharegistro', models.DateTimeField(auto_now_add=True)),
                ('copr_fechacambio', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': '"gpracticasut"."conceptospracticas"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GrupoIntegrante',
            fields=[
                ('grin_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('grin_nombre', models.CharField(max_length=300)),
                ('grin_descripcion', models.TextField(blank=True, null=True)),
                ('grin_registradorpor', models.CharField(blank=True, max_length=30, null=True)),
                ('grin_fecharegistro', models.DateTimeField(auto_now_add=True)),
                ('grin_fechacambio', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': '"gpracticasut"."grupointegrante"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LugaresPraticas',
            fields=[
                ('lupr_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('lupr_codigo', models.CharField(blank=True, max_length=20, null=True)),
                ('lupr_nombre', models.CharField(max_length=300)),
                ('lupr_description', models.TextField(blank=True, null=True)),
                ('lupr_estado', models.BooleanField(default=True)),
                ('lupr_registradorpor', models.CharField(blank=True, max_length=30, null=True)),
                ('lupr_fecharegistro', models.DateTimeField(auto_now_add=True)),
                ('lupr_fechacambio', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': '"gpracticasut"."lugarespraticas"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SolictudPratica',
            fields=[
                ('solp_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('solp_nombre', models.CharField(max_length=300)),
                ('solp_description', models.TextField(blank=True, null=True)),
                ('solp_anio', models.CharField(blank=True, max_length=4, null=True)),
                ('solp_numerodias', models.PositiveIntegerField(blank=True, null=True)),
                ('solp_numerodocentes', models.PositiveIntegerField(blank=True, null=True)),
                ('solp_numeroestudiantes', models.PositiveIntegerField(blank=True, null=True)),
                ('solp_numerocondutores', models.PositiveIntegerField(blank=True, null=True)),
                ('solp_fechainiciopratica', models.DateTimeField(blank=True, null=True)),
                ('solp_fechafinpratica', models.DateTimeField(blank=True, null=True)),
                ('solp_duraciondoc', models.FloatField(blank=True, null=True)),
                ('solp_cvehiculoproctica', models.CharField(choices=[('PROPIO', 'PROPIO'), ('CONTRATADO', 'CONTRATADO')], max_length=50)),
                ('solp_costototalpratica', models.FloatField(blank=True, null=True)),
                ('solp_registradorpor', models.CharField(blank=True, max_length=30, null=True)),
                ('solp_fecharegistro', models.DateTimeField(auto_now_add=True)),
                ('solp_fechacambio', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': '"gpracticasut"."solicitudpraticas"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoIntegrante',
            fields=[
                ('tiin_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('tiin_nombre', models.CharField(max_length=300)),
                ('tiin_descripcion', models.TextField(blank=True, null=True)),
                ('tiin_registradorpor', models.CharField(blank=True, max_length=30, null=True)),
                ('tiin_fecharegistro', models.DateTimeField(auto_now_add=True)),
                ('tiin_fechacambio', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': '"gpracticasut"."tipointegrante"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VhiculosPracticas',
            fields=[
                ('vper_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('vper_registradorpor', models.CharField(blank=True, max_length=30, null=True)),
                ('vper_fecharegistro', models.DateTimeField(auto_now_add=True)),
                ('vper_fechacambio', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': '"gpracticasut"."vehiculopracticas"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PersonaIntegrante',
            fields=[
                ('pein_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('pein_registradorpor', models.CharField(blank=True, max_length=30, null=True)),
                ('pein_fecharegistro', models.DateTimeField(auto_now_add=True)),
                ('pein_fechacambio', models.DateTimeField(auto_now=True)),
                ('pege_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.personageneral')),
                ('pers_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academicoglobal.persona')),
                ('solp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionpratica.solictudpratica')),
                ('tiin_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionpratica.tipointegrante')),
            ],
            options={
                'db_table': '"gpracticasut"."personaintegrante"',
                'unique_together': {('pege_id', 'solp_id')},
            },
        ),
    ]
