# Generated by Django 3.1.4 on 2021-10-03 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MarcaVehiculos',
            fields=[
                ('mveh_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('mveh_nombre', models.CharField(max_length=100)),
                ('mveh_descripcion', models.TextField(blank=True, db_column='MVEH_DESCRIPTION', null=True)),
                ('mveh_registradorpor', models.CharField(blank=True, max_length=30, null=True)),
                ('mveh_fecharegistro', models.DateTimeField(auto_now_add=True)),
                ('mveh_fechacambio', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': '"gpracticasut"."marcavehiculos"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoVehiculo',
            fields=[
                ('tveh_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('tveh_nombre', models.CharField(max_length=100)),
                ('tveh_descripcion', models.TextField(blank=True, db_column='TVEH_DESCRIPTION', null=True)),
                ('tveh_registradorpor', models.CharField(blank=True, max_length=30, null=True)),
                ('tveh_fecharegistro', models.DateTimeField(auto_now_add=True)),
                ('tveh_fechacambio', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': '"gpracticasut"."tipovehiculo"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Vehiculos',
            fields=[
                ('vehi_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('vehi_placa', models.CharField(max_length=10)),
                ('vehi_combustible', models.CharField(choices=[('GASOLINA', 'GASOLINA'), ('ACPM', 'ACPM')], max_length=20)),
                ('vehi_capacidadcombustible', models.IntegerField(blank=True, null=True)),
                ('vehi_capacidadpasajeros', models.IntegerField()),
                ('vehi_capacidadaaforopasajeros', models.IntegerField(blank=True, null=True)),
                ('vehi_registradorpor', models.CharField(blank=True, max_length=30, null=True)),
                ('vehi_fecharegistro', models.DateTimeField(auto_now_add=True)),
                ('vehi_fechacambio', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': '"gpracticasut"."vehiculos"',
                'managed': False,
            },
        ),
    ]
