"""
Django settings for gpracticasut project.

Generated by 'django-admin startproject' using Django 3.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'ay$sm+_%u+q!7mc)zac50y8zjvju_!(8mnn91s+zo!6px2r5ul'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'general',
    'academicoglobal',
    'academico',
    'gestionflota',
    'gestionpratica',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'gpracticasut.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR, 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'gpracticasut.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'praticasut4',
        'USER': 'postgres',
        'PASSWORD': '123456',
        'HOST': 'localhost',
        'PORT': '5432',
    },
    'academicoacademico': {
                'ENGINE': 'django.db.backends.oracle',
                'NAME': 'NIVELA',
                #'NAME': 'UTOLACAD1',
                'USER': 'ACADEMICO',
                #'USER': 'WEBSERVICEERP',
                #'PASSWORD': '8CDUAkGKEBxjzuh9***',
                'PASSWORD': '123456789',
                'HOST': '192.168.107.54',
                #'HOST': '192.168.125.20',
                'PORT': '1521',
                'OPTIONS': {
                    'threaded': True,
                },
            },
    'academicoglobal': {
                'ENGINE': 'django.db.backends.oracle',
                'NAME': 'NIVELA',
                #'NAME': 'UTOLACAD1',
                'USER': 'GLOBAL',
                #'USER': 'WEBSERVICEERP',
                #'PASSWORD': '8CDUAkGKEBxjzuh9***',
                'PASSWORD': '123456789',
                'HOST': '192.168.107.54',
                #'HOST': '192.168.125.20',
                'PORT': '1521',
                'OPTIONS': {
                    'threaded': True,
                },
            },
    'academicogeneral': {
                    'ENGINE': 'django.db.backends.oracle',
                    'NAME': 'NIVELA',
                    #'NAME': 'UTOLACAD1',
                    'USER': 'GENERAL',
                    #'USER': 'WEBSERVICEERP',
                    #'PASSWORD': '8CDUAkGKEBxjzuh9***',
                    'PASSWORD': '123456789',
                    'HOST': '192.168.107.54',
                    #'HOST': '192.168.125.20',
                    'PORT': '1521',
                    'OPTIONS': {
                        'threaded': True,
                    },
                },
    'gpracticasut': {
                    'ENGINE': 'django.db.backends.oracle',
                    'NAME': 'NIVELA',
                    #'NAME': 'UTOLACAD1',
                    'USER': 'GPRACTICASUT',
                    #'USER': 'WEBSERVICEERP',
                    #'PASSWORD': '8CDUAkGKEBxjzuh9***',
                    'PASSWORD': '123456789',
                    'HOST': '192.168.107.54',
                    #'HOST': '192.168.125.20',
                    'PORT': '1521',
                    'OPTIONS': {
                        'threaded': True,
                    },
                }
}

DATABASE_ROUTERS = [
    'academico.routers.AcademicoRouter',
    'general.routers.GeneralRouter',
    'academicoglobal.routers.AcademicoGlobalRouter',
    'gestionflota.routers.GestionFlotaRouter',
    'gestionpratica.routers.GestionPracticaRouter',
]
# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = BASE_DIR, 'static'

