# Generated by Django 3.1.4 on 2021-10-03 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PersonaGeneral',
            fields=[
                ('pege_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('pege_tipopersona', models.IntegerField(blank=True, null=True)),
                ('pege_direccion', models.CharField(blank=True, max_length=100, null=True)),
                ('pege_mail', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': '"general"."personageneral"',
                'managed': False,
            },
        ),
    ]
